# Generated by Django 3.1.6 on 2021-09-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=55, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(default='none', max_length=10)),
                ('username', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_staff', models.IntegerField(default=False)),
                ('is_active', models.IntegerField(default=True)),
                ('is_superuser', models.IntegerField(default=False)),
            ],
            options={
                'db_table': 'korisnici',
            },
        ),
        migrations.CreateModel(
            name='Predmeti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('kod', models.CharField(max_length=16, unique=True)),
                ('program', models.TextField(default='None')),
                ('bodovi', models.IntegerField(blank=True, null=True)),
                ('sem_redovni', models.IntegerField(blank=True, null=True)),
                ('sem_izvanredni', models.IntegerField(blank=True, null=True)),
                ('izborni', models.CharField(max_length=2)),
                ('nositelj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'db_table': 'predmeti',
            },
        ),
        migrations.CreateModel(
            name='Uloge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'uloge',
            },
        ),
        migrations.CreateModel(
            name='Upisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='nepolozen', max_length=64)),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.predmeti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
            options={
                'db_table': 'upisi',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.uloge'),
        ),
    ]
